### PR TITLE
Add disclaimer in regards to royalties and copyright

### PR DESCRIPTION
**Pull request by ItsMitchh**
A small disclaimer is added into the requirements section to enforce that we're not liable for licenses.

### CODE REVIEW

**Review by Vaalyn — APPROVED** [review]
LGTM 👍

**Comment by ItsMitchh** [comment]
All good, I was just double checking this was working correctly 👍

**Comment by ItsMitchh** [comment]
bump?

**Comment by Vaalyn** [comment]
> bump?

Thanks for the reminder 👍

**Pull request merged**
